apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    env: dev
    app: myapp
  namespace: banku
type: Opaque
stringData:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres