apiVersion: v1
kind: Secret
metadata:
  name: todoapp-secret
  labels:
    env: dev
    app: todoapp
  namespace: banku
type: Opaque
stringData:
  DB_ENGINE: django.db.backends.postgresql
  DB_HOST: my-postgres
  DB_NAME: postgres
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_PORT: "5432"